def eng_kr():
    f = open("LOG.txt", 'r')
    text = f.read()
    f.close()
    text.replace("q", "ㅂ")
    text.replace("w", "ㅈ")
    text.replace("e", "ㄷ")
    text.replace("r", "ㄱ")
    text.replace("t", "ㅅ")
    text.replace("y", "ㅛ")
    text.replace("u", "ㅕ")
    text.replace("i", "ㅑ")
    text.replace("o", "ㅐ")
    text.replace("p", "ㅔ")
    text.replace("a", "ㅁ")
    text.replace("s", "ㄴ")
    text.replace("d", "ㅇ")
    text.replace("f", "ㄹ")
    text.replace("g", "ㅎ")
    text.replace("h", "ㅗ")
    text.replace("j", "ㅓ")
    text.replace("k", "ㅏ")
    text.replace("l", "ㅣ")
    text.replace("z", "ㅋ")
    text.replace("x", "ㅌ")
    text.replace("c", "ㅊ")
    text.replace("v", "ㅍ")
    text.replace("b", "ㅠ")
    text.replace("n", "ㅜ")
    text.replace("m", "ㅡ")
    text.replace("/", "?")
    return text
